### ISSUE TITLE
Tests failing on F24 and F25

### ISSUE THREAD

**Issue by Fale** [sybrenstuvel/python-rsa#52]
I'm compiling 3.4 for EL6, EL7, F22, F23, F24, and F25.
It works properly on all but F24 and F25. It could be a different python version (F24 and F25 are running with python 3.5.1), I guess.
This is how it fails:

```
======================================================================
ERROR: test_load_from_disk (tests.test_load_save_keys.PemTest)
Test loading a PEM file from disk.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rsa-3.4/tests/test_load_save_keys.py", line 150, in test_load_from_disk
    with open(fname, mode='rb') as privatefile:
FileNotFoundError: [Errno 2] No such file or directory: '/builddir/build/BUILD/rsa-3.4/tests/private.pem'
======================================================================
ERROR: test_load_from_disk (tests.test_load_save_keys.PemTest)
Test loading a PEM file from disk.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rsa-3.4/tests/test_load_save_keys.py", line 150, in test_load_from_disk
    with open(fname, mode='rb') as privatefile:
FileNotFoundError: [Errno 2] No such file or directory: '/builddir/build/BUILD/rsa-3.4/tests/private.pem'
----------------------------------------------------------------------
```

For complete log, they are [here](http://koji.fedoraproject.org/koji/taskinfo?taskID=13381989)

**Comment by sybrenstuvel** [comment]
What are EL6, EL7, F22, F23, F24, and F25?

**Comment by Fale** [comment]
Sorry,
EL = Enterprise Linux (Red Hat Enterprise Linux, CentOS, Scientific Linux, Oracle Linux)
F = Fedora

**Comment by sybrenstuvel** [comment]
Since I don't have any of these Linuxes, I can't investigate this issue. `tests/private.pem` is part of the Git repo, so if the tests can't find that file there is something wrong with the way the build is performed. On Ubuntu Linux it runs fine on Python 3.5.1, so that can't be it.

**Comment by Fale** [comment]
I think #53 will fix this bug :)

**Comment by sybrenstuvel** [comment]
Please re-test this now that #53 has been merged.

**Comment by Fale** [comment]
This can not be tested until a new release is done and pushed to pypi

**Comment by sybrenstuvel** [comment]
I just released 3.4.1, which includes only manifest changes, including this change.

**Comment by Fale** [comment]
It seems like even in 3.4.1 the missing pem file problem persists. The file is present so it seems to be some different problem this time. I'll try to make it work :)

**Comment by Fale** [comment]
Worked perfectly :) thanks
